version: "3"

volumes:
    postgres_data:
        driver: local

services:
    app:
        container_name: realworld-app
        build:
            args:
                user: ${USER}
                uid: ${USER_ID}
            context: ./
            dockerfile: docker/php/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - realworld

    db:
        container_name: realworld-db
        image: postgres:12.7
        restart: always
        ports:
            - ${LOCAL_DB_PORT}:5432
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - realworld

    nginx:
        container_name: realworld-nginx
        image: nginx:stable
        restart: always
        ports:
            - ${LOCAL_NGINX_PORT}:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - realworld

networks:
    realworld:
        driver: bridge
